### ISSUE TITLE
Unable to Exclude a User

### ISSUE THREAD

**Issue by jichizhang** [arastu/likelo#5]
I excluded several users in the configuration, however, the bot still automatically like their tweets.

![](http://i.imgur.com/d2atcam.png)
![](http://i.imgur.com/GSh6rk3.png)

**Comment by arastu** [comment]
Hi @JJaicmkmy 
Thanks for report
This feature is not implemented yet, I am trying to implement exclude user on the weekends.

**Comment by arastu** [comment]
@JJaicmkmy feature added :)
For excluding user, enter twitter username without @
